#***NumPy Special Arrays***

*   Array filled with 0's
*   Array filled with 1's
*   Create an empty array
*   Array with all its elements set as a specific given value 
*   An array with a range of elements
*   Array diagonal elements filled with 1's
*   Diagonal matrix
*   Identity matrix
*   Create an array with values that are spaced linearly in a specified interval

### **1. Array filled with 0's**

***Syntax:*** **numpy.zeros(shape, [dtype], [order])**

shape = Dimension; an int for 1D array, tuple with n entries for n-D array

dtype = Data type of array elements. Default float

order = Style of storing multidimensional array. C: C-style, F: Fortran style

In [4]:
import numpy as np

# An array filled with 0's
# By default dimension is one
zeros1 = np.zeros(4)
print(zeros1)
print("Dimension:",zeros1.ndim)

[0. 0. 0. 0.]
Dimension: 1

In [5]:
# An array of 2 dimension filled with 0's with 3 rows and 4 cols
zeros2 = np.zeros((3,4))
print(zeros2)
print("Dimension:",zeros2.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Dimension: 2

In [6]:
# An array of 3 dimension filled with 0's with 2 rows and 4 cols and 3 stacks on z-axis
zeros3 = np.zeros((2,4,3))
print(zeros3)
print("Dimension:",zeros3.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
Dimension: 3

### **2. Array filled with 1's**

***Syntax:*** **numpy.ones(shape, [dtype], [order])**

shape = Dimension; an int for 1D array, tuple with n entries for n-D array

dtype = Data type of array elements. Default float

order = Style of storing multidimensional array. C: C-style, F: Fortran style

In [7]:
# An array of 2 dimension filled with 1's with 3 rows and 4 cols
ones1 = np.ones((3,4), dtype = int)
print(ones1)
print("Dimension:",ones1.ndim)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Dimension: 2

### **3. Empty array**

*numpy.empty() creates a NumPy matrix/array without initializing it with any values. It contains junk values.*

***Syntax:*** **numpy.empty(shape, [dtype], [order])**

shape = Dimension; an int for 1D array, tuple with n entries for n-D array

dtype = Data type of array elements. Default float

order = Style of storing multidimensional array. C: C-style, F: Fortran style

In [23]:
# An empty array of 2 dimension with with 3 rows and 4 cols
emp1 = np.empty((3,4), dtype = int)
print(emp1)
print("Dimension:",emp1.ndim)

[[29091488        0        0        0]
 [       0        0        0        0]
 [       0        0        0        0]]
Dimension: 2

### **4. Array with all its elements set as a specific given value**

***Syntax:*** **numpy.full(shape, fill_value, [dtype], [order])**

shape = Dimension; an int for 1D array, tuple with n entries for n-D array

fill_value = Value to fill the array

dtype = Data type of array elements. Default float

order = Style of storing multidimensional array. C: C-style, F: Fortran style

In [9]:
# An array of 2 dimension with with 3 rows and 4 cols filled with 95 as it's value
full1 = np.full((3,4), fill_value = 95,dtype = int)
print(full1)
print("Dimension:",full1.ndim)

[[95 95 95 95]
 [95 95 95 95]
 [95 95 95 95]]
Dimension: 2

### **5. Array with a range of elements**

*Returns an 1D array filled will elements between a given range*

***Syntax:*** **numpy.arange([start], stop, [step], [dtype])**

start = Start of interval range. Default = 0

stop = End of interval range (exclusive)

step = step size of interval. Default = 1

dtype = Data type of array elements. Default float

In [10]:
# An array containing values between range 0 and 5
ran1 = np.arange(6, dtype = int)
print(ran1)
print("Dimension:",ran1.ndim)

[0 1 2 3 4 5]
Dimension: 1

In [11]:
# An array containing values between range 1 and 10
ran2 = np.arange(1, 11, dtype = int)
print(ran2)
print("Dimension:",ran2.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension: 1

### **6. Array diagonal elements filled with 1's**

*Returns a 2D array with 1's as the diagonal and 0's elsewhere*

***Syntax:*** **numpy.eye(N, [M], [k], [dtype])**

N = No of rows

M = No of columns. By default = No of rows

k = Diagonal we require; k>0 means diagonal above main diagonal or vice versa.

dtype = Data type of array elements. Default float

In [12]:
# A 2D array with 3 rows and 3 cols and diagonal filled with 1's
eye1 = np.eye(3, dtype = int)
print(eye1)
print("Dimension:",eye1.ndim)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
Dimension: 2

In [13]:
# A 2D array with 4 rows and 5 cols and diagonal just below the main diagonal filled with 1's
eye1 = np.eye(N = 4, M = 5, k = -1, dtype = int)
print(eye1)
print("Dimension:",eye1.ndim)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
Dimension: 2

### **7. Diagonal matrix**

*Extract a diagonal or construct a diagonal array.*

***Syntax:*** **numpy.eye(v, [k])**

v = array_like; If v is a 2-D array return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.

k = Diagonal we require; k>0 means diagonal above main diagonal or vice versa.

In [14]:
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Returns the diagonal of the array as 2D array is sent into the parameter
diag1 = np.diag(arr)
print(diag1)

# Returns the k = -1 diagonal of the array
diag2 = np.diag(arr, k = -1)
print(diag2)

[0 4 8]
[3 7]

In [15]:
# Returns a 2D diagonal matrix as 1D array is sent into the parameter 
diag3 = np.diag(diag1)
print(diag3)

[[0 0 0]
 [0 4 0]
 [0 0 8]]

### **8. Identity matrix**

*Return the identity array. The identity array is a square array with ones on the main diagonal.*

***Syntax:*** **numpy.identity(n, [dtype])**

n = Number of rows (and columns) in n x n output.

dtype = Data type of array elements. Default float

In [16]:
# Creates an identity matrix of dimension 3x3
id1 = np.identity(3, dtype = int)
print(id1)
print("Dimension:",id1.ndim)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
Dimension: 2

**Diffenence between np.identity() and np.eye()**


---
*np.identity() returns a square matrix (special case of a 2D-array) which is an identity matrix with the main diagonal (i.e. 'k=0') as 1's and the other values as 0's. you can't change the diagonal k here.*

*np.eye() returns a 2D-array, which fills the diagonal, i.e. 'k' which can be set, with 1's and rest with 0's.*

### **9. Linearly spaced array**

*Returns an array of evenly spaced numbers over a specified interval. Returns num evenly spaced samples, calculated over the interval [start, stop]. The endpoint of the interval can optionally be excluded.*

***Syntax:*** **numpy.linspace(start, stop, num, [endpoint], [retstep], [dtype], [axis])**

start = The starting value of the sequence

stop = The end value of the sequence. Inclusive by default

num = Number of samples to generate. Default is 50. Must be non-negative.

endpoint = If True, stop is the last sample. Otherwise, it is not included. Default is True.

retstep = If True, return (samples, step), where step is the spacing between samples.

dtype =  The type of the output array. If dtype is not given, the data type is inferred from start and stop. The inferred dtype will never be an integer; float is chosen even if the arguments would produce an array of integers.

axis = The axis in the result to store the samples. Relevant only if start or stop are array-like. By default (0), the samples will be along a new axis inserted at the beginning. Use -1 to get an axis at the end.

In [17]:
# Returns an array of 5 evenly spaced number between 2 and 3(inclusive)
lin1 = np.linspace(2.0, 3.0, num=5)
print(lin1)

[2.   2.25 2.5  2.75 3.  ]

In [18]:
# Returns an array of 5 evenly spaced number between 2 and 3(exclusive)
lin2 = np.linspace(2.0, 3.0, num=5, endpoint=False)
print(lin2)

[2.  2.2 2.4 2.6 2.8]

In [19]:
# Returns an (array, steps) of 5 evenly spaced number between 2 and 3(inclusive)
lin3 = np.linspace(2.0, 3.0, num=5, retstep=True)
print(lin3)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)